# These are supported funding model platforms

# github: [ihsan710]
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# liberapay: 
# issuehunt: 
# otechie: 
# lfm: 
# custom: 
